config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sports#index"
  get 'sports/search'
  resources :sports do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [

    { id: 1, name: '---' },
    { id: 2, name: '霧島市国分' },
    { id: 3, name: '霧島市隼人' },
    { id: 4, name: '霧島市霧島' },
    { id: 5, name: '霧島市牧園' },
    { id: 6, name: '霧島市福山' },
    { id: 7, name: '霧島市横川' },
    { id: 8, name: '霧島市溝辺' }

  ]

  include ActiveHash::Associations
  has_many :sports
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [

    { id: 1, name: '---' },
    { id: 2, name: '野球' },
    { id: 3, name: 'サッカー' },
    { id: 4, name: 'バスケットボール' },
    { id: 5, name: 'バレーボール' },
    { id: 6, name: '剣道' },
    { id: 7, name: '柔道' },
    { id: 8, name: '空手' },
    { id: 9, name: 'テニス' },
    { id: 10, name: 'バトミントン' },
    { id: 11, name: 'フットサル' }
    # { id: 12, name: '空手' },
    # { id: 13, name: '空手' },
    # { id: 14, name: '空手' },
    # { id: 15, name: '空手' },
    # { id: 16, name: '空手' },

  ]

  include ActiveHash::Associations
  has_many :sports
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sport
  belongs_to :user
end

app/models/sport.rb
class Sport < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :messages

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :category

  with_options presence: true do
    validates :title
    validates :sport_text
    validates :price
    validates :image

    with_options numericality: { other_than: 1 } do
      validates :category_id
      validates :area_id
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sports
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  with_options presence: true do
    validates :nickname
    with_options format: { with: /\A[ぁ-んァ-ン一-龥々]+\z/ } do
      validates :last_name
      validates :first_name
    end
    with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
      validates :kana_last_name
      validates :kana_first_name
    end
    validates :phone_number, length: { maximum: 11 }, format: { with: /\A[0-9]+\z/ }
    validates :birthday, format: { with: /\A\d{4}-\d{2}-\d{2}\z/ }
    validates :main_sport
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :email, :password, :last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :main_sport,
                                             :birthday])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.create(message_params)
    redirect_to "/sports/#{message.sport.id}"
  end

  private

  def message_params
    params.require(:message).permit(:comment).merge(user_id: current_user.id, sport_id: params[:sport_id])
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :search_sport, only: [:index, :search, :show]

  def index
    @sports = Sport.all
    @sport = Sport.order('created_at DESC')
    set_sport_column
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @sport = Sport.find(params[:id])
    @message = Message.new
    @messages = @sport.messages.includes(:user)
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])
    if @sport.update(sport_params)
      redirect_to sport_path(@sport)
    else
      render :edit
    end
  end

  def destroy
    if @sport.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @results = @p.result.includes(:category)
  end

  private

  def sport_params
    params.require(:sport).permit(:title, :sport_text, :category_id, :area_id, :price, :image).merge(user_id: current_user.id)
  end

  def search_sport
    @p = Sport.ransack(params[:q])
  end

  def set_sport_column
    @sport_name = Sport.select('category_id.name').distinct
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :last_name, :first_name, :kana_last_name, :kana_first_name,
                                 :phone_number, :main_sport, :birthday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>FAMISPO</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag "item-sample.png", class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= "商品名" %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= 999,999,999 %></p>
          <p class='item-price-sub-text'><%= '配送料負担' %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= "販売価格" %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area 'hoge', class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area 'hoge', class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field "hoge",class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、スポーツクラブ検索アプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FAMISPOについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FAMISPO利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FAMISPOを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FAMISPOについて</h2>
      <ul>
        <li><%= link_to 'FAMISPOガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FAMISPOロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("name.jpg", class:"logo-white"), "#" %>
  <p>© FAMISPO</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("name.jpg", class:"furima-icon"), "/" %>

    <%# <div class="search-form"> %>
      <%= search_form_for @p, url: sports_search_path , class:"search-form" do |f| %>
        <%= f.collection_select :category_id_eq, Category.all, :id, :name, {}, class: "input-box" %>
      <%# <%= link_to(new_sport_path, class: 'purchase-btn') do %> 
      <%#= button_tag type: :submit, class:"search-button" do %>
      <%# end %>
        <%= f.submit '',:class=>"search-button" %>
          <%#= image_tag "search.png" , class:"search-icon" %>
      <% end %>
    <%# </div> %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
    </ul>
    <ul class='lists-right'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname"%> </li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%> </li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login"%></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li> 
    <% end %>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FAMISPO利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "name.jpg", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("name.jpg", class:"second-logo"), "/" %>
</header>

app/views/sports/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      あなたの生活に新しい習慣を!!
    </h2>
    <p class='service-explain'>
      FAMISPOはだれでもかんたんに募集・検索できる
    </p>
    <p class='service-explain'>
      スポーツクラブ検索アプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FAMISPOが選ばれる理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に登録できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索もスムーズ！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>

  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規登録', new_sport_path, class: "subtitle" %>
    <ul class='item-lists'>
      <% @sport.each do |sport| %>
      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <li class='list'>
        <%= link_to sport_path(sport.id) do %>
        <div class='item-img-content'>
          <%= image_tag sport.image, class: "item-img" if sport.image.attached?%>

          <%# 商品が売れていればsold outを表示しましょう %>
          <%# <div class='sold-out'> %>
            <%# <span>Sold Out!!</span> %>
          <%# </div>  %>
          <%# //商品が売れていればsold outを表示しましょう %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= sport.title %>
          </h3>
          <div class='item-price'>
            <span><%= sport.category.name %><br><%= sport.area.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>

      <%# 商品がない場合は以下のダミー商品が表示されるようにしましょう %>
      <%# 商品がある場合は表示されないようにしましょう %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <%# //商品がある場合は表示されないようにしましょう %>
      <%# //商品がない場合は以下のダミー商品が表示されるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_sport_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/sports/search.html.erb
<%= render "shared/header" %>
<h1>
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>
<%# <% if @results.length !=0 %>
  <%# <% @results.each do |result| %>
    <%# <td> %>
    <%# <br> %>
    <%# <li> %>
      <%# <%= result.title %>
      <%# <%= result.size %>
      <%# <%= result.status %>
      <%# <%= result.price %>
      <%# <%= result.category.name %>
    <%# </li> %>
  <%# <% end %>
<%# <% else %>
  <%# 該当する商品はありません %>
<%# <% end %>
<%# <br> %>
<%= link_to 'トップページへ戻る', root_path %>
<%= render "shared/footer" %>

app/views/sports/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @sport.title %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @sport.image ,class:"item-box-img" %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
      <%# <div class="sold-out"> %>
        <%# <span>Sold Out!!</span> %>
      <%# </div> %>
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>


    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% if user_signed_in? %>
      <% if current_user.id == @sport.user_id %>
        <%= link_to "投稿の編集", edit_sport_path, method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", sport_path(@sport.id), method: :delete, class:"item-destroy" %>
      <%# <% else %> %>
        <%# 商品が売れていない場合はこちらを表示しましょう %>
        <%# <%= link_to "購入画面に進む", "#" ,class:"item-red-btn"%> %>
        <%# //商品が売れていない場合はこちらを表示しましょう %>
      <% end %>
    <% end %>
    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= @sport.sport_text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @sport.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @sport.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">活動地域</th>
          <td class="detail-value"><%= @sport.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">参加費</th>
          <td class="detail-value"><%= @sport.price %></td>
        </tr>
        <tr>
          <th class="detail-item">＃</th>
          <td class="detail-value"><%= "" %></td>
        </tr>
        <tr>
          <th class="detail-item">＃</th>
          <td class="detail-value"><%= "" %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な投稿の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <%# <form> %>
    <%= form_with model: [@sport, @message], local: true do |form| %>
      <%# <textarea class="comment-text"></textarea> %>
      <%= form.text_area :comment, placeholder: "コメントを入力して下さい", class:"comment-text" %>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <%# <button type="submit" class="comment-btn"> %>
      <%= form.submit "コメントする", class: "comment-btn" %>
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <%# <span>コメントする<span> %>
      <%# </button> %>
     <%# </form> %>
    <% end %>
    </div>
    <div class="comments-list">
      <h4 class = "comment-title">＜コメント一覧＞</h4>
      <% @messages.each do |message| %>
        <p>
          <strong><%= link_to message.user.nickname, "#" %>：</strong>
          <%= message.comment %>
          <%# <div class="message-date"> %>
          <!-- 投稿した時刻を出力する -->
          <%= l message.created_at %>
          <%# </div> %>
        </p>
      <% end %>
    </div>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の投稿
    </a>
    <a href="#" class="change-item-btn">
      後ろの投稿 ＞
    </a>
  </div>
  <%# 詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
  <a href="#" class="another-item"><%= "登録のカテゴリー名" %>をもっと見る</a>
  <%# //詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
</div>

<%= render "shared/footer" %>